name: Build Reviung41 Firmware

on:
  push:
    branches:
      - main
  workflow_dispatch: # permite ejecutarlo manualmente desde la UI de GitHub

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Zephyr dependencies
        uses: zmkfirmware/zmk-docker-action@v1

      - name: Build firmware for Reviung41
        run: |
          west init -l app
          west update
          west zephyr-export
          source zephyr/zephyr-env.sh
          west build -s app -b reviung41

      - name: Upload firmware artifact
        uses: actions/upload-artifact@v4
        with:
          name: reviung41-firmware
          path: build/zephyr/zmk.uf2
